// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKbtfzrPFnQciScFkjE6FxM2MrlBpS4ww',
    appId: '1:57651732127:web:d3727aa8bd409fcca6ccaa',
    messagingSenderId: '57651732127',
    projectId: 'e-learning-app-cd4b7',
    authDomain: 'e-learning-app-cd4b7.firebaseapp.com',
    storageBucket: 'e-learning-app-cd4b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOsO26TsZox45svriQ9bJP0MudPnBye_w',
    appId: '1:57651732127:android:177f50a8c0a7b2a9a6ccaa',
    messagingSenderId: '57651732127',
    projectId: 'e-learning-app-cd4b7',
    storageBucket: 'e-learning-app-cd4b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-JFFEI2XH0oBMXJZwUuX7QZcKAT9dLSo',
    appId: '1:57651732127:ios:39728d66250ac057a6ccaa',
    messagingSenderId: '57651732127',
    projectId: 'e-learning-app-cd4b7',
    storageBucket: 'e-learning-app-cd4b7.appspot.com',
    iosClientId: '57651732127-dqn8m1jtmebp8oqppkmppp2n2sr6amq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterShopAppDbestech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-JFFEI2XH0oBMXJZwUuX7QZcKAT9dLSo',
    appId: '1:57651732127:ios:b04bee9718c35b44a6ccaa',
    messagingSenderId: '57651732127',
    projectId: 'e-learning-app-cd4b7',
    storageBucket: 'e-learning-app-cd4b7.appspot.com',
    iosClientId: '57651732127-epo9jdnsm56em9rojqnuvmurpc9civli.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterShopAppDbestech.RunnerTests',
  );
}
